apiVersion: v1
kind: ConfigMap
metadata:
  name: gopal-db-config
  namespace: gopal-app-dev
data:
  DB_HOST: "gopalpgdev.postgres.database.azure.com"
  DB_PORT: "5432"
  DB_NAME: "gopalappdev"
  DB_SSL: "require"
