apiVersion: v1
kind: ConfigMap
metadata:
  name: gopal-db-config
  namespace: gopal-app-prod
data:
  DB_HOST: "gopalpgprod.postgres.database.azure.com"
  DB_PORT: "5432"
  DB_NAME: "gopalappprod"
  DB_SSL: "require"
