apiVersion: v1
kind: ConfigMap
metadata:
  name: gopal-db-config
  namespace: gopal-app-qa
data:
  DB_HOST: "gopalpgqa.postgres.database.azure.com"
  DB_PORT: "5432"
  DB_NAME: "gopalappqa"
  DB_SSL: "require"
